- name: Create disks(s) and instance(s)
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    state: active
    machine_type: g1-small
    hosts_b:
      - gluster-1b
      - gluster-2b
      - gluster-3b
    disk_type: pd-standard
    disk_size: 500
    zone: europe-west1-b

  tasks:
    - name: Launch instances
      gce:
          instance_names: "{{ hosts_b|join(',') }}"
          machine_type: "{{ machine_type }}"
          image: centos-7
          tags: gluster
          zone: "{{ zone }}"
          state: "{{ state }}"
      register: gce

    - name: Add host to gluster group
      add_host: hostname={{ item.public_ip }} groupname=gluster
      with_items: "{{gce.instance_data | default({})}}"

    - name: Create disks
      gce_pd:
          name: "{{ item }}-data"
          instance_name: "{{ item }}"
          size_gb: "{{ disk_size }}"
          disk_type: "{{ disk_type }}"
          zone: "{{ zone }}"
          mode: READ_WRITE
          state: "{{ state }}"
      with_items: "{{hosts_b}}"

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_ip }} port=22 delay=3 timeout=60
      with_items: "{{gce.instance_data | default({})}}"
      when: gce.instance_data is defined

- name: Configure instance(s) with gluster
  hosts: gluster
  become: true
  vars:
    sysctl:
    - name: vm.dirty_ratio
      value: 5
    - name: vm.dirty_background_ratio
      value: 2
    volumes:
    - name: certvol
      type: "replica 3"
      quota: False
      bitrot: enable
      parameters:
        # - allow 10.*
        # - client.event-threads 4
        # - server.event-threads 4
        - performance.cache-size 100MB
        # - performance.io-thread-count 16
        # - performance.client-io-threads on
        # - performance.io-cache on
        # - performance.readdir-ahead on
        - performance.flush-behind off
        # - cluster.lookup-optimize on
      hosts:
        - gluster-1b
        - gluster-2b
        - gluster-3b
        # - gluster-2b
        # - gluster-2d
    - name: user_spaces
      type: "replica 3"
      quota: True
      bitrot: enable
      parameters:
        - performance.cache-size 100MB
        - performance.flush-behind off
      hosts:
        - gluster-1b
        - gluster-2b
        - gluster-3b
    - name: reacctdbvol
      type: "replica 3"
      quota: False
      bitrot: enable
      parameters:
        - performance.cache-size 100MB
        - performance.flush-behind off
      hosts:
        - gluster-1b
        - gluster-2b
        - gluster-3b
    mount_point: /mnt
  roles:
    # - stackdriver_agent
    - install
    - create_gluster_volumes
